# Join traffic with pollution data

In [1]:
import pandas as pd

In [13]:
traffic = pd.read_csv("database\\traffic_date_value.csv")
pollution = pd.read_csv("database\\pollution_date_value.csv")

In [14]:
df_final = traffic.merge(pollution, left_on='FECHA_HORA', right_on='FECHA_HORA', how='left')

In [15]:
df_final

,FECHA_HORA,IDELEM,INTENSIDAD,OCUPACION,CARGA,MAGNITUD,TECNICA,CODIGO_ESTACION,NOMBRE_ESTACION,COD_MAGNITUD,NOMBRE_MAGNITUD,ABREVIATURA,UNIDAD,COD_TECNICA,TECNICA_MEDIDA,VALOR_CONTAMINACION
0,2017-01-01 00:00:00,3910,129.000000,1.000000,3.750000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
1,2017-01-01 00:00:00,3911,151.000000,0.666667,3.666667,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
2,2017-01-01 00:00:00,3913,106.750000,0.000000,3.000000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
3,2017-01-01 00:00:00,3914,145.500000,0.250000,3.750000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
4,2017-01-01 00:00:00,3915,118.250000,0.250000,2.750000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477808,2024-12-31 23:00:00,3913,57.333333,0.000000,1.333333,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0
477809,2024-12-31 23:00:00,3914,56.500000,0.000000,1.250000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0
477810,2024-12-31 23:00:00,3915,43.000000,0.000000,0.666667,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0
477811,2024-12-31 23:00:00,3917,50.000000,0.000000,1.000000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0
477812,2024-12-31 23:00:00,5547,70.750000,0.000000,0.500000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0

In [16]:
df_final = df_final.drop(columns=['MAGNITUD', 'TECNICA', 'CODIGO_ESTACION', 'NOMBRE_ESTACION', 'COD_MAGNITUD', 
                 'NOMBRE_MAGNITUD', 'ABREVIATURA', 'UNIDAD', 'COD_TECNICA',	'TECNICA_MEDIDA'])

In [17]:
df_final

,FECHA_HORA,IDELEM,INTENSIDAD,OCUPACION,CARGA,VALOR_CONTAMINACION
0,2017-01-01 00:00:00,3910,129.000000,1.000000,3.750000,40.0
1,2017-01-01 00:00:00,3911,151.000000,0.666667,3.666667,40.0
2,2017-01-01 00:00:00,3913,106.750000,0.000000,3.000000,40.0
3,2017-01-01 00:00:00,3914,145.500000,0.250000,3.750000,40.0
4,2017-01-01 00:00:00,3915,118.250000,0.250000,2.750000,40.0
...,...,...,...,...,...,...
477808,2024-12-31 23:00:00,3913,57.333333,0.000000,1.333333,62.0
477809,2024-12-31 23:00:00,3914,56.500000,0.000000,1.250000,62.0
477810,2024-12-31 23:00:00,3915,43.000000,0.000000,0.666667,62.0
477811,2024-12-31 23:00:00,3917,50.000000,0.000000,1.000000,62.0
477812,2024-12-31 23:00:00,5547,70.750000,0.000000,0.500000,62.0

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb
from sklearn.metrics import mean_squared_error