# Join traffic with pollution data

In [1]:
import pandas as pd

In [2]:
traffic = pd.read_csv("database\\traffic_date_value.csv")
pollution = pd.read_csv("database\\pollution_date_value.csv")

In [3]:
df_final = traffic.merge(pollution, left_on='FECHA_HORA', right_on='FECHA_HORA', how='left')

In [4]:
df_final

,FECHA_HORA,IDELEM,INTENSIDAD,OCUPACION,CARGA,MAGNITUD,TECNICA,CODIGO_ESTACION,NOMBRE_ESTACION,COD_MAGNITUD,NOMBRE_MAGNITUD,ABREVIATURA,UNIDAD,COD_TECNICA,TECNICA_MEDIDA,VALOR_CONTAMINACION
0,2017-01-01 00:00:00,3910,129.000000,1.000000,3.750000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
1,2017-01-01 00:00:00,3911,151.000000,0.666667,3.666667,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
2,2017-01-01 00:00:00,3913,106.750000,0.000000,3.000000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
3,2017-01-01 00:00:00,3914,145.500000,0.250000,3.750000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
4,2017-01-01 00:00:00,3915,118.250000,0.250000,2.750000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477808,2024-12-31 23:00:00,3913,57.333333,0.000000,1.333333,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0
477809,2024-12-31 23:00:00,3914,56.500000,0.000000,1.250000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0
477810,2024-12-31 23:00:00,3915,43.000000,0.000000,0.666667,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0
477811,2024-12-31 23:00:00,3917,50.000000,0.000000,1.000000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0
477812,2024-12-31 23:00:00,5547,70.750000,0.000000,0.500000,8.0,8.0,28079011.0,Av. Ramón y Cajal,8.0,Dióxido de Nitrógeno,NO2,µg/m3,8.0,Quimioluminiscencia,62.0

In [5]:
df_final = df_final.drop(columns=['MAGNITUD', 'TECNICA', 'CODIGO_ESTACION', 'NOMBRE_ESTACION', 'COD_MAGNITUD', 
                 'NOMBRE_MAGNITUD', 'ABREVIATURA', 'UNIDAD', 'COD_TECNICA',	'TECNICA_MEDIDA'])

In [6]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 477813 entries, 0 to 477812
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   FECHA_HORA           477813 non-null  object
 1   IDELEM               477813 non-null  int64
 2   INTENSIDAD           477811 non-null  float64
 3   OCUPACION            475064 non-null  float64
 4   CARGA                477611 non-null  float64
 5   VALOR_CONTAMINACION  467061 non-null  float64
dtypes: float64(4), int64(1), object(1)
memory usage: 21.9+ MB

In [7]:
df_final = df_final.dropna()

In [8]:
df_final['VALOR_CONTAMINACION'].unique()

array([ 40.,  44.,  46.,  43.,  33.,  37.,  26.,  36.,  50.,  56.,  47.,
        42.,  45.,  60.,  78.,  87.,  81.,  66.,  28.,  21.,  20.,  14.,
        18.,  35.,  49.,  41.,  62.,  74.,  85.,  76.,  80.,  75.,  54.,
        48.,  27.,  29.,  58.,  63.,  55.,  79.,  84.,  83.,  82.,  86.,
       105., 110., 117., 112.,  59.,  61.,  57.,  72., 103., 129., 106.,
       111.,  53.,  69.,  88.,  32.,  30.,  51.,  90.,  94.,  92., 113.,
       104., 108., 136., 107.,  64.,  65.,  25.,  39., 181., 121., 125.,
        23.,  24.,  17.,  34., 124., 152., 154., 133.,  31.,  97.,  73.,
        93., 116.,  77.,  71.,  89.,  91.,  99., 100., 127., 132., 101.,
        67.,  52.,  68.,  96.,  16.,  15.,   9.,  10.,   6.,  11.,  38.,
        70.,  19.,  22.,  98.,   8.,  13.,   7.,   5.,   4.,  12., 179.,
       155., 139., 137., 122., 102.,  95., 109., 143., 172., 123., 119.,
       138., 158., 256., 251., 194.,   3.,   0., 120., 128., 142., 114.,
       126., 135., 115., 157., 177.,   2., 134., 118., 146., 164., 190.,
       163., 151., 197., 168., 183.,   1., 149., 140., 160., 130., 144.,
       141., 171., 264., 237., 192., 185., 150., 162., 186., 131., 180.,
       231., 147., 202., 167., 246., 232., 203., 169., 258., 195., 305.,
       289., 201., 270., 200., 222., 153., 196., 229., 187., 165., 292.,
       254., 239., 170., 247., 215., 252., 293., 227., 182., 281., 310.,
       285., 241., 175., 148., 242., 191., 184., 178., 189., 206., 220.,
       249., 188., 166., 156., 173., 207., 161., 174., 245., 204., 209.,
       238., 198., 236., 224., 223., 233., 145., 199., 221., 217., 240.,
       214., 205., 193., 225., 267., 311., 331., 230., 216., 211., 176.,
       213., 159., 228., 218.])

In [9]:
df_final

,FECHA_HORA,IDELEM,INTENSIDAD,OCUPACION,CARGA,VALOR_CONTAMINACION
0,2017-01-01 00:00:00,3910,129.000000,1.000000,3.750000,40.0
1,2017-01-01 00:00:00,3911,151.000000,0.666667,3.666667,40.0
2,2017-01-01 00:00:00,3913,106.750000,0.000000,3.000000,40.0
3,2017-01-01 00:00:00,3914,145.500000,0.250000,3.750000,40.0
4,2017-01-01 00:00:00,3915,118.250000,0.250000,2.750000,40.0
...,...,...,...,...,...,...
477808,2024-12-31 23:00:00,3913,57.333333,0.000000,1.333333,62.0
477809,2024-12-31 23:00:00,3914,56.500000,0.000000,1.250000,62.0
477810,2024-12-31 23:00:00,3915,43.000000,0.000000,0.666667,62.0
477811,2024-12-31 23:00:00,3917,50.000000,0.000000,1.000000,62.0
477812,2024-12-31 23:00:00,5547,70.750000,0.000000,0.500000,62.0

In [8]:
df_final.to_csv("database\\model_data.csv", index=False)