# Traffic Data Cleaning

In [ ]:
import os
import pandas as pd

In [2]:
file = "database\\traffic_data\\2025-05-31T19-26-43.564598.xml"
df = pd.read_xml(file)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5613 entries, 0 to 5612
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fecha_hora      1 non-null      object
 1   idelem          5612 non-null   float64
 2   descripcion     5598 non-null   object
 3   accesoAsociado  4807 non-null   float64
 4   intensidad      5612 non-null   float64
 5   ocupacion       5612 non-null   float64
 6   carga           5612 non-null   float64
 7   nivelServicio   5612 non-null   float64
 8   intensidadSat   5302 non-null   float64
 9   error           5598 non-null   object
 10  subarea         5302 non-null   float64
 11  st_x            5612 non-null   object
 12  st_y            5612 non-null   object
 13  velocidad       310 non-null    float64
dtypes: float64(9), object(5)
memory usage: 614.1+ KB

In [3]:
df['fecha_hora'] = df['fecha_hora'][0]
#df = df.drop(columns=['velocidad'], axis=1)
df = df.iloc[1:].reset_index(drop=True)

In [55]:
df.describe()

,idelem,accesoAsociado,intensidad,ocupacion,carga,nivelServicio,intensidadSat,subarea,velocidad
count,5612.000000,4.807000e+03,5612.000000,5612.000000,5612.000000,5612.000000,5302.000000,5302.000000,310.000000
mean,6970.980043,2.257133e+06,406.193870,7.220955,21.912509,0.345688,1979.022822,42620.756696,62.903226
std,2677.579609,2.730555e+06,601.009318,14.289481,19.501706,0.620646,1165.289832,76920.875440,26.656213
min,3395.000000,0.000000e+00,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,0.000000,-1.000000
25%,4840.000000,3.017035e+05,80.000000,1.000000,8.000000,0.000000,1200.000000,1711.000000,57.000000
50%,6032.500000,7.631040e+05,223.000000,3.000000,17.000000,0.000000,1500.000000,3201.000000,71.000000
75%,10231.250000,4.716002e+06,480.500000,6.000000,30.000000,1.000000,3000.000000,110003.000000,80.750000
max,11429.000000,9.734024e+06,6720.000000,100.000000,275.000000,3.000000,18830.000000,310042.000000,110.000000

In [56]:
df.head()

,fecha_hora,idelem,descripcion,accesoAsociado,intensidad,ocupacion,carga,nivelServicio,intensidadSat,error,subarea,st_x,st_y,velocidad
0,31/05/2025 19:20:05,3840.0,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,512003.0,120.0,1.0,16.0,0.0,830.0,S,101.0,"441617,090594015","4475765,7692796",NaN
1,31/05/2025 19:20:05,3841.0,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,103004.0,220.0,2.0,14.0,0.0,1800.0,N,101.0,"441706,039143845","4475769,10491597",NaN
2,31/05/2025 19:20:05,3842.0,Pº Recoletos N-S - Almirante-Prim,109002.0,960.0,7.0,44.0,1.0,2500.0,N,101.0,"441319,371258338","4474841,15423716",NaN
3,31/05/2025 19:20:05,3843.0,Pº Recoletos S-N - Pl. Cibeles- Recoletos,109001.0,999.0,3.0,24.0,0.0,3500.0,N,101.0,"441301,63298559","4474763,7275141",NaN
4,31/05/2025 19:20:05,3844.0,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,101001.0,0.0,99.0,48.0,1.0,4050.0,S,101.0,"441606,236261728","4476129,4605423",NaN

In [4]:
streets = ["Ramón y Cajal", "Ramon y Cajal", "Concha Espina", "Principe de Vergara", "Principe Vergara"]
# s1-s3, s1-s4, s2-s3, s2-s4, s3-s4
# s1 = "Ramón y Cajal"
# s2 = "Ramon y Cajal"
# s3 = "Concha Espina"
# s4 = "Principe de Vergara"

# streets = [s1, s2, s3, s4]
df_filtered = pd.DataFrame() 

for i in range(len(streets)):
    for j in range(i+1, len(streets)):
        cond1 = df['descripcion'].str.contains(streets[i], case=False, na=False)
        cond2 = df['descripcion'].str.contains(streets[j], case=False, na=False)
        matches = df[cond1 & cond2]

        print(f"Searching... {streets[i]} + {streets[j]} → {len(matches)} coincidences")
        df_filtered = pd.concat([df_filtered, matches], ignore_index=True)

Searching... Ramón y Cajal + Ramon y Cajal → 0 coincidences
Searching... Ramón y Cajal + Concha Espina → 0 coincidences
Searching... Ramón y Cajal + Principe de Vergara → 0 coincidences
Searching... Ramón y Cajal + Principe Vergara → 1 coincidences
Searching... Ramon y Cajal + Concha Espina → 0 coincidences
Searching... Ramon y Cajal + Principe de Vergara → 0 coincidences
Searching... Ramon y Cajal + Principe Vergara → 3 coincidences
Searching... Concha Espina + Principe de Vergara → 1 coincidences
Searching... Concha Espina + Principe Vergara → 3 coincidences
Searching... Principe de Vergara + Principe Vergara → 0 coincidences

In [5]:
df_filtered.head()

,fecha_hora,idelem,descripcion,accesoAsociado,intensidad,ocupacion,carga,nivelServicio,intensidadSat,error,subarea,st_x,st_y,velocidad
0,31/05/2025 19:20:05,3914.0,Ramón y Cajal O-E - Principe Vergara-Marcenado,405003.0,640.0,5.0,24.0,0.0,2550.0,N,101.0,"442614,070599179","4478104,31804049",NaN
1,31/05/2025 19:20:05,3910.0,"Ramon y Cajal, 7 E-O - Principe Vergara-Marcenado",404004.0,640.0,5.0,24.0,0.0,2450.0,N,101.0,"442703,668178519","4478108,85061351",NaN
2,31/05/2025 19:20:05,3911.0,"Principe Vergara, 207 S-N - Pradillo-Ramon y C...",404001.0,720.0,4.0,29.0,1.0,2450.0,N,101.0,"442534,685252877","4477944,17351396",NaN
3,31/05/2025 19:20:05,3917.0,Ramon y Cajal E-O - Principe Vergara-Rodriguez...,415004.0,499.0,3.0,26.0,1.0,1900.0,N,101.0,"442489,997368006","4478113,94188072",NaN
4,31/05/2025 19:20:05,5547.0,Principe de Vergara S-N - Concha Espina-Pl.Rep...,6130001.0,780.0,2.0,12.0,0.0,4500.0,N,302.0,"442557,229455396","4478194,86075925",NaN

In [6]:
df_filtered["descripcion"].unique()

array(['Ramón y Cajal O-E - Principe Vergara-Marcenado ',
       'Ramon y Cajal, 7 E-O - Principe Vergara-Marcenado',
       'Principe Vergara, 207 S-N - Pradillo-Ramon y Cajal',
       'Ramon y Cajal E-O - Principe Vergara-Rodriguez Marin',
       'Principe de Vergara S-N - Concha Espina-Pl.República Ecuador',
       'Principe Vergara N-S - Pl. Republica Ecuador-Concha Espina',
       'Principe Vergara N-S - Concha Espina-Pl. Cataluña',
       'Concha Espinal O-E - Rodriguez Marin-Principe Vergara'],
      dtype=object)

In [ ]:
list_idelem = df_filtered["idelem"].unique().astype(int)
list_idelem

array([3914, 3910, 3911, 3917, 5547, 3913, 3915, 3916])

In [1]:
list_idelem = [3914, 3910, 3911, 3917, 5547, 3913, 3915, 3916]

# Historical Data Cleaning

In [2]:
def detect_delimiter(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        first_line = f.readline()
        if first_line.count(';') > first_line.count(','):
            return ';'
        else:
            return ','

def load_all_csv_filtered(folder_path, list_idelem):
    all_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
    df_list = []

    for f in all_files:
        file_path = os.path.join(folder_path, f)
        delimiter = detect_delimiter(file_path)
        
        try:
            df = pd.read_csv(file_path, sep=delimiter)
            if 'id' in df.columns and 'idelem' not in df.columns:
                df = df.rename(columns={'id': 'idelem'})

            if 'idelem' in df.columns:
                df_filtered = df[df['idelem'].isin(list_idelem)]
                df_list.append(df_filtered)
            else:
                print(f"Advertencia: '{f}' no contiene ni 'idelem' ni 'id'.")

        except Exception as e:
            print(f"Error al leer '{f}': {e}")

    if df_list:
        return pd.concat(df_list, ignore_index=True)
    else:
        return pd.DataFrame()

In [4]:
historical_data_folder = "database/traffic_historical_data_2017_2024"
df = load_all_csv_filtered(historical_data_folder, list_idelem)

In [5]:
df

,idelem,fecha,identif,tipo_elem,intensidad,ocupacion,carga,vmed,error,periodo_integracion
0,3910,2017-01-01 00:00:00,04002,PUNTOS MEDIDA URBANOS,49.0,0.0,1.0,0.0,N,7
1,3917,2017-01-01 00:15:00,04011,PUNTOS MEDIDA URBANOS,48.0,0.0,0.0,0.0,N,5
2,3913,2017-01-01 00:00:00,04007,PUNTOS MEDIDA URBANOS,67.0,0.0,2.0,0.0,N,6
3,3915,2017-01-01 00:00:00,04009,PUNTOS MEDIDA URBANOS,64.0,0.0,1.0,0.0,N,5
4,3910,2017-01-01 00:30:00,04002,PUNTOS MEDIDA URBANOS,103.0,0.0,2.0,0.0,N,15
...,...,...,...,...,...,...,...,...,...,...
1904870,5547,2024-12-31 22:30:00,NaN,URB,68.0,0.0,1.0,0.0,N,5
1904871,5547,2024-12-31 23:00:00,NaN,URB,49.0,0.0,0.0,0.0,N,9
1904872,5547,2024-12-31 23:15:00,NaN,URB,77.0,0.0,0.0,0.0,N,12
1904873,5547,2024-12-31 23:30:00,NaN,URB,67.0,0.0,1.0,0.0,N,14
1904874,5547,2024-12-31 23:45:00,NaN,URB,90.0,0.0,1.0,0.0,N,6

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1904875 entries, 0 to 1904874
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   idelem               int64
 1   fecha                datetime64[ns]
 2   identif              object
 3   tipo_elem            object
 4   intensidad           float64
 5   ocupacion            float64
 6   carga                float64
 7   vmed                 float64
 8   error                object
 9   periodo_integracion  int64
dtypes: datetime64[ns](1), float64(4), int64(2), object(3)
memory usage: 145.3+ MB

In [8]:
df['fecha'] = pd.to_datetime(df['fecha'])

In [10]:
df = df.sort_values(by='fecha', ascending=True)

In [11]:
df

,idelem,fecha,identif,tipo_elem,intensidad,ocupacion,carga,vmed,error,periodo_integracion
0,3910,2017-01-01 00:00:00,04002,PUNTOS MEDIDA URBANOS,49.0,0.0,1.0,0.0,N,7
16,3917,2017-01-01 00:00:00,04011,PUNTOS MEDIDA URBANOS,40.0,0.0,1.0,0.0,N,1
13,3911,2017-01-01 00:00:00,04003,PUNTOS MEDIDA URBANOS,47.0,0.0,1.0,0.0,N,3
21,3914,2017-01-01 00:00:00,04008,PUNTOS MEDIDA URBANOS,63.0,0.0,3.0,0.0,N,7
11,5547,2017-01-01 00:00:00,61035,PUNTOS MEDIDA URBANOS,77.0,0.0,1.0,0.0,N,6
...,...,...,...,...,...,...,...,...,...,...
1890037,3913,2024-12-31 23:45:00,NaN,URB,46.0,0.0,1.0,0.0,N,7
1887067,3911,2024-12-31 23:45:00,NaN,URB,75.0,1.0,3.0,0.0,N,4
1884095,3910,2024-12-31 23:45:00,NaN,URB,40.0,0.0,1.0,0.0,N,4
1901899,3917,2024-12-31 23:45:00,NaN,URB,40.0,0.0,1.0,0.0,N,2
1904874,5547,2024-12-31 23:45:00,NaN,URB,90.0,0.0,1.0,0.0,N,6

In [ ]:
# Save df as csv for every year
# df.to_csv(historical_data_folder + ".csv", index=False)

# Final cleaning

In [22]:
df_trafico = pd.read_csv("database\\traffic_historical_data_2017_2024.csv", parse_dates=['fecha'])

In [23]:
df_trafico = df_trafico.drop(columns=['identif', 'tipo_elem', 'error', 'vmed', 'periodo_integracion']).reset_index(drop=True)

In [24]:
df_trafico

         idelem               fecha  intensidad  ocupacion  carga
0          3910 2017-01-01 00:00:00        49.0        0.0    1.0
1          3917 2017-01-01 00:00:00        40.0        0.0    1.0
2          3911 2017-01-01 00:00:00        47.0        0.0    1.0
3          3914 2017-01-01 00:00:00        63.0        0.0    3.0
4          5547 2017-01-01 00:00:00        77.0        0.0    1.0
...         ...                 ...         ...        ...    ...
1904870    3913 2024-12-31 23:45:00        46.0        0.0    1.0
1904871    3911 2024-12-31 23:45:00        75.0        1.0    3.0
1904872    3910 2024-12-31 23:45:00        40.0        0.0    1.0
1904873    3917 2024-12-31 23:45:00        40.0        0.0    1.0
1904874    5547 2024-12-31 23:45:00        90.0        0.0    1.0

[1904875 rows x 5 columns]

In [25]:
# Redondear la columna 'fecha' a la hora más cercana hacia abajo
df_trafico['fecha_hora'] = df_trafico['fecha'].dt.floor('H')  # Trunca a la hora
df_trafico

C:\Users\andre\AppData\Local\Temp\ipykernel_18768\1242489729.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_trafico['fecha_hora'] = df_trafico['fecha'].dt.floor('H')  # Trunca a la hora

,idelem,fecha,intensidad,ocupacion,carga,fecha_hora
0,3910,2017-01-01 00:00:00,49.0,0.0,1.0,2017-01-01 00:00:00
1,3917,2017-01-01 00:00:00,40.0,0.0,1.0,2017-01-01 00:00:00
2,3911,2017-01-01 00:00:00,47.0,0.0,1.0,2017-01-01 00:00:00
3,3914,2017-01-01 00:00:00,63.0,0.0,3.0,2017-01-01 00:00:00
4,5547,2017-01-01 00:00:00,77.0,0.0,1.0,2017-01-01 00:00:00
...,...,...,...,...,...,...
1904870,3913,2024-12-31 23:45:00,46.0,0.0,1.0,2024-12-31 23:00:00
1904871,3911,2024-12-31 23:45:00,75.0,1.0,3.0,2024-12-31 23:00:00
1904872,3910,2024-12-31 23:45:00,40.0,0.0,1.0,2024-12-31 23:00:00
1904873,3917,2024-12-31 23:45:00,40.0,0.0,1.0,2024-12-31 23:00:00
1904874,5547,2024-12-31 23:45:00,90.0,0.0,1.0,2024-12-31 23:00:00

In [32]:
# Agrupar por 'idelem' y 'fecha_hora', calculando la media del resto
df_trafico_agrupado = df_trafico.groupby(['fecha_hora', 'idelem']).agg({
    'intensidad': 'mean',
    'ocupacion': 'mean',
    'carga': 'mean',
}).reset_index()

In [33]:
df_trafico_agrupado

                fecha_hora  idelem  intensidad  ocupacion     carga
0      2017-01-01 00:00:00    3910  129.000000   1.000000  3.750000
1      2017-01-01 00:00:00    3911  151.000000   0.666667  3.666667
2      2017-01-01 00:00:00    3913  106.750000   0.000000  3.000000
3      2017-01-01 00:00:00    3914  145.500000   0.250000  3.750000
4      2017-01-01 00:00:00    3915  118.250000   0.250000  2.750000
...                    ...     ...         ...        ...       ...
477808 2024-12-31 23:00:00    3913   57.333333   0.000000  1.333333
477809 2024-12-31 23:00:00    3914   56.500000   0.000000  1.250000
477810 2024-12-31 23:00:00    3915   43.000000   0.000000  0.666667
477811 2024-12-31 23:00:00    3917   50.000000   0.000000  1.000000
477812 2024-12-31 23:00:00    5547   70.750000   0.000000  0.500000

[477813 rows x 5 columns]

In [34]:
df_trafico_agrupado.describe()

,fecha_hora,idelem,intensidad,ocupacion,carga
count,477813,477813.000000,477811.000000,475064.000000,477611.000000
mean,2021-02-07 21:18:27.719546880,4119.044220,470.901169,3.570216,18.368958
min,2017-01-01 00:00:00,3910.000000,0.000000,0.000000,0.000000
25%,2018-09-24 02:00:00,3911.000000,127.250000,0.500000,4.250000
50%,2021-08-01 12:00:00,3915.000000,389.500000,2.250000,14.500000
75%,2023-04-18 17:00:00,3917.000000,769.750000,5.250000,30.250000
max,2024-12-31 23:00:00,5547.000000,16960.500000,100.000000,100.000000
std,NaN,541.493315,376.829725,4.659593,15.761954

In [35]:
df_trafico_agrupado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 477813 entries, 0 to 477812
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   fecha_hora  477813 non-null  datetime64[ns]
 1   idelem      477813 non-null  int64
 2   intensidad  477811 non-null  float64
 3   ocupacion   475064 non-null  float64
 4   carga       477611 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1)
memory usage: 18.2 MB

In [ ]:
# df_trafico_agrupado.to_csv("database\\traffic_date_value" + ".csv", index=False)